# Generated by Django 4.0.3 on 2022-10-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
